# Generated by Django 5.1.15 on 2026-09-07 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0002_alter_broadcast_sent_by'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broadcastlog',
            name='lead',
        ),
        migrations.AddField(
            model_name='broadcastlog',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_logs', to='companies.contact'),
        ),
    ]
