# Generated by Django 5.1.15 on 2026-08-31 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('company_source', models.CharField(blank=True, max_length=255)),
                ('potential_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stage', models.CharField(choices=[('NEW', 'Prospek Baru'), ('CONTACTED', 'Hubungi'), ('NEGOTIATION', 'Presentasi/Negosiasi'), ('WON', 'Won'), ('LOST', 'Lost')], default='NEW', max_length=20)),
                ('tag', models.CharField(choices=[('HOT', 'Hot'), ('COLD', 'Cold')], default='COLD', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='accounts.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
