# Generated by Django 5.1.15 on 2026-08-31 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
