# Generated by Django 5.1.15 on 2026-09-07 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activitylog_activity_type_activitylog_is_completed_and_more'),
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='lead',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='deals.deal'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('CALL', 'Call'), ('EMAIL', 'Email'), ('MEETING', 'Meeting'), ('NOTE', 'Note'), ('FOLLOW_UP', 'Follow Up')], default='NOTE', max_length=20),
        ),
    ]
